class CfgPatches
{
	class Capsule_Enoch
	{
		addonRootClass="Capsule";
		requiredAddons[]=
		{
			"Capsule"
		};
		requiredVersion=0.1;
		units[]={};
		weapons[]={};
	};
};
class CfgSoundShaders
{
	class UrbanTree_Birds_Day_SoundShader
	{
		samples[]=
		{
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\HouseWren_Forest_Day_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\HouseWren_Forest_Day_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\HouseWren_Forest_Day_Distant_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\HouseWren_Forest_Day_Distant_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_03",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_04",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_05",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_06",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_07",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_08",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_09",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_10",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_11",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_12",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_13",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_14",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_15",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_16",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_17",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_18",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_19",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_20",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_21",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_22",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_03",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_04",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_05",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_06",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_07",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_08",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_09",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_10",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_11",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_12",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_13",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_14",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_15",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_16",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_17",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_18",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_19",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_20",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\CarWren_Forest_Day_Distant_21",
				1
			}
		};
		volume="(rain factor[0.7,0.4]) * (1 - night) * (houses) * (wind factor[0.7,0.5]) * (shooting factor [0.6,1])";
		range=25;
	};
	class Wind_Trees_Creaks_SoundShader
	{
		limitation=1;
		rangeCurve[]=
		{
			{0,0},
			{5,0.25},
			{10,0.5},
			{15,1},
			{20,1}
		};
	};
	class Wind_Trees_Creaks_Close_SoundShader
	{
		limitation=1;
		range=20;
		rangeCurve[]=
		{
			{0,1},
			{5,1},
			{10,0.5},
			{15,0.25},
			{20,0}
		};
		samples[]=
		{
			{
				"a3\sounds_f_enoch\assets\environment\spotfx\wind\wind_trees_creaks_close_01",
				1
			},
			{
				"a3\sounds_f_enoch\assets\environment\spotfx\wind\wind_trees_creaks_close_02",
				1
			},
			{
				"a3\sounds_f_enoch\assets\environment\spotfx\wind\wind_trees_creaks_close_03",
				1
			},
			{
				"a3\sounds_f_enoch\assets\environment\spotfx\wind\wind_trees_creaks_close_04",
				1
			},
			{
				"a3\sounds_f_enoch\assets\environment\spotfx\wind\wind_trees_creaks_close_05",
				1
			},
			{
				"a3\sounds_f_enoch\assets\environment\spotfx\wind\wind_trees_creaks_close_06",
				1
			},
			{
				"a3\sounds_f_enoch\assets\environment\spotfx\wind\wind_trees_creaks_close_07",
				1
			},
			{
				"a3\sounds_f_enoch\assets\environment\spotfx\wind\wind_trees_creaks_close_08",
				1
			},
			{
				"a3\sounds_f_enoch\assets\environment\spotfx\wind\wind_trees_creaks_close_09",
				1
			}
		};
		volume="1.2 * (wind factor [0.4, 0.7])";
	};
	class Forest_Bg_Night_01_SoundShader
	{
		samples[]=
		{
			{
				"A3\Sounds_F_Enoch\Assets\Environment\Backgrounds\Forest\Forest_Bg_Noon",
				1
			}
		};
		volume=0;
	};
	class WindMeadows_Low_Enoch_SoundShader
	{
		samples[]=
		{
			{
				"A3\Sounds_F_Enoch\Assets\Environment\Backgrounds\Wind\wind_meadows_light",
				1
			}
		};
	};
	class Insect_Day_SoundShader
	{
		samples[]=
		{
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Insects\Insect_Day_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Insects\Insect_Day_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Insects\Insect_Day_03",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Insects\Insect_Day_04",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Insects\Insect_Day_05",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Insects\Insect_Day_06",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Insects\Insect_Day_07",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Insects\Insect_Day_08",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Insects\Insect_Day_09",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Insects\Insect_Day_10",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Insects\Insect_Day_11",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Insects\Insect_Day_12",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Insects\Insect_Raspy_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Insects\Insect_Raspy_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Insects\Insect_Raspy_03",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Insects\Insect_Raspy_04",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Insects\Insect_Raspy_05",
				1
			}
		};
	};
	class Forest_Woodpecker_SoundShader
	{
		samples[]=
		{
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Woodpecker_Distant_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Woodpecker_Distant_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Woodpecker_Distant_03",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Woodpecker_Distant_04",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Woodpecker_Distant_05",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Woodpecker_Distant_06",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Woodpecker_Distant_07",
				1
			}
		};
	};
	class Forest_Whippoorwhill_Night_Dawn_SoundShader
	{
		samples[]=
		{
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_01_Forest_Night_Dawn_Distant_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_01_Forest_Night_Dawn_Distant_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_01_Forest_Night_Dawn_Distant_03",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_01_Forest_Night_Dawn_Distant_04",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_01_Forest_Night_Dawn_Distant_05",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_01_Forest_Night_Dawn_Distant_06",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_01_Forest_Night_Dawn_Distant_07",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_01_Forest_Night_Dawn_Distant_08",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_01_Forest_Night_Dawn_Distant_09",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_01_Forest_Night_Dawn_Distant_10",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_01_Forest_Night_Dawn_Distant_11",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_02_Forest_Night_Dawn_Distant_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_02_Forest_Night_Dawn_Distant_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_02_Forest_Night_Dawn_Distant_03",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_02_Forest_Night_Dawn_Distant_04",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_02_Forest_Night_Dawn_Distant_05",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_02_Forest_Night_Dawn_Distant_06",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_02_Forest_Night_Dawn_Distant_07",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_02_Forest_Night_Dawn_Distant_08",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_02_Forest_Night_Dawn_Distant_09",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Whippoorwhills\Whippoorwhill_02_Forest_Night_Dawn_Distant_10",
				1
			}
		};
	};
	class Forest_Birds_All_Night_SoundShader
	{
		samples[]=
		{
			{
				"A3\Sounds_F\environment\animals\birds\owl1",
				1
			},
			{
				"A3\Sounds_F\environment\animals\birds\owl2",
				1
			},
			{
				"A3\Sounds_F\environment\animals\birds\owl3",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Raven_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Raven_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Raven_03",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Raven_04",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Raven_05",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Raven_06",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Raven_07",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Raven_08",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Mid\Night\bird01_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Mid\Night\bird01_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Mid\Night\bird01_03",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Mid\Night\bird01_08",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Mid\Night\bird03_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Mid\Night\bird03_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Mid\Night\bird03_03",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Mid\Night\bird04_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Mid\Night\bird04_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Night\bird01_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Night\bird01_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Night\bird01_03",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Night\bird01_08",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Night\bird03_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Night\bird03_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Night\bird03_03",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Night\bird04_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Night\bird04_02",
				1
			}
		};
	};
	class Forest_Wrens_Forest_Day_SoundShader
	{
		samples[]=
		{
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_03",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_04",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_05",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_06",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_07",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_08",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_09",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_10",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_11",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_12",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_13",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_14",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_15",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_16",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_17",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_Distant_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_Distant_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_Distant_03",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_Distant_04",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_Distant_05",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_Distant_06",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_Distant_07",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_Distant_08",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_Distant_09",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_Distant_10",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_Distant_11",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_Distant_12",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_Distant_13",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_Distant_14",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_Distant_15",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_Distant_16",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wren_Forest_Day_Distant_17",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wrentit_Forest_Day_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wrentit_Forest_Day_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wrentit_Forest_Day_Distant_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Wrentit_Forest_Day_Distant_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Warbler_Forest_Day_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Warbler_Forest_Day_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Warbler_Forest_Day_Distant_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\Warbler_Forest_Day_Distant_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\DarkEyedJunco_Forest_Day_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Wrens\DarkEyedJunco_Forest_Day_Distant_01",
				1
			}
		};
	};
	class Forest_Birds_All_Day_SoundShader
	{
		samples[]=
		{
			{
				"A3\Sounds_F\environment\animals\birds\owl1",
				0.36
			},
			{
				"A3\Sounds_F\environment\animals\birds\owl2",
				0.36
			},
			{
				"A3\Sounds_F\environment\animals\birds\owl3",
				0.36
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_03",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_04",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_05",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_06",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_07",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_08",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_09",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_10",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_11",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_12",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_13",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_14",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_15",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_16",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_17",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_18",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_19",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_20",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_21",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_22",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_23",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_24",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_25",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_26",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_27",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_28",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_29",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_30",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_31",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_32",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_33",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_34",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_35",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_36",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_37",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_38",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_39",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_40",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_41",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_42",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_43",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_44",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_45",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_46",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_47",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_48",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_49",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_50",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_51",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_52",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_53",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_54",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_55",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_56",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_57",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_58",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_59",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_60",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_61",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_62",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_63",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_64",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_65",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_66",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_67",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_68",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_69",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_70",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Close\Birds_Forest_Day_71",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_03",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_04",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_05",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_06",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_07",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_08",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_09",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_10",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_11",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_12",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_13",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_14",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_15",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_16",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_17",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_18",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_19",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_20",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_21",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_22",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_23",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_24",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_25",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_26",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_27",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_28",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_29",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_30",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_31",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_32",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_33",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_34",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_35",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_36",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_37",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_38",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_39",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_40",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_41",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_42",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_43",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_44",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_45",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_46",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_47",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_48",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_49",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_50",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_51",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_52",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_53",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_54",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_55",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_56",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_57",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_58",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_59",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_60",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_61",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_62",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_63",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_64",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_65",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_66",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_67",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_68",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_69",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_70",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\birds\Forest\Distant\Birds_Forest_Day_Distant_71",
				1
			}
		};
	};
	class Deercall_Forest_Night_SoundShader
	{
		samples[]=
		{
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Animals\Deer_Call_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Animals\Deer_Call_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Animals\Deer_Call_03",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Animals\Deer_Call_04",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Animals\Deer_Call_05",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Animals\Deer_Call_06",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Animals\Deer_Call_07",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Animals\Deer_Call_08",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Animals\Deer_Call_09",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Animals\Deer_Call_10",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Animals\Deer_Call_11",
				1
			}
		};
	};
	class Wolves_Night_SoundShader
	{
		samples[]=
		{
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Animals\Wolves_01",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Animals\Wolves_02",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Animals\Wolves_03",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Animals\Wolves_04",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Animals\Wolves_05",
				1
			},
			{
				"A3\Sounds_F_Enoch\Assets\Environment\SpotFx\Fauna\Animals\Wolves_06",
				1
			}
		};
	};
};
class CfgSoundSets
{
	class UrbanTree_Birds_Day_SoundSet
	{
		soundShaders[]=
		{
			"UrbanTree_Birds_Day_SoundShader"
		};
		volumeFactor="0.8 * 1.6";
		volumeRandomizer=0.5;
		frequencyFactor=1;
		frequencyRandomizer=0.5;
		spatial=1;
		doppler=0;
		loop=0;
		delay=7;
		delayRandomizer=2.5;
		volumeCurve="birdsVolumeCurve";
		sound3DProcessingType="Birds3DProcessingType";
	};
	class Forest_Birds_All_Day_SoundSet
	{
		volumeRandomizer=0.5;
		frequencyFactor=0.75;
		frequencyRandomizer=6;
		delay=7;
		delayRandomizer=2.5;
		volumeCurve="birdsVolumeCurve";
		sound3DProcessingType="Birds3DProcessingType";
	};
	class Forest_Birds_All_Night_SoundSet
	{
		volumeRandomizer=0.5;
		frequencyFactor=1;
		frequencyRandomizer=0.5;
		delay=10;
		delayRandomizer=2.5;
		volumeCurve="birdsVolumeCurve";
		sound3DProcessingType="Birds3DProcessingType";
	};
	class Forest_Woodpecker_SoundSet
	{
		delay=50;
		delayRandomizer=60;
		volumeCurve="birdsVolumeCurve";
		sound3DProcessingType="Birds3DProcessingType";
	};
	class Forest_Whippoorwhill_Night_Dawn_SoundSet
	{
		volumeCurve="birdsVolumeCurve";
		sound3DProcessingType="Birds3DProcessingType";
	};
	class Forest_Wrens_Forest_Day_SoundSet
	{
		volumeCurve="birdsVolumeCurve";
		sound3DProcessingType="Birds3DProcessingType";
	};
	class Deercall_Forest_Night_SoundSet
	{
		volumeCurve="birdsVolumeCurve";
		sound3DProcessingType="Birds3DProcessingType";
	};
	class Wolves_Night_SoundSet
	{
		volumeCurve="birdsVolumeCurve";
		sound3DProcessingType="Birds3DProcessingType";
	};
	class Wind_Trees_Creaks_SoundSet
	{
		soundShaders[]+=
		{
			"Wind_Trees_Creaks_Close_SoundShader"
		};
		volumeFactor=0.5;
		volumeRandomizer=2;
		frequencyFactor=1;
		frequencyRandomizer=3;
		frequencyRandomizerMin=1;
		volumeCurve="CreakAttenuationCurve";
		sound3DProcessingType="WindTreesCreaks_3DProcessingType";
		soundShadersLimit=1;
	};
};
